#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("Plugin.ImageCropper.Resource", IsApplication=false)]

namespace Plugin.ImageCropper
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public static int camera_crop_height = 2130837504;
			
			// aapt resource value: 0x7f020001
			public static int camera_crop_width = 2130837505;
			
			// aapt resource value: 0x7f020002
			public static int indicator_autocrop = 2130837506;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050002
			public static int discard = 2131034114;
			
			// aapt resource value: 0x7f050000
			public static int image = 2131034112;
			
			// aapt resource value: 0x7f050003
			public static int rotateLeft = 2131034115;
			
			// aapt resource value: 0x7f050004
			public static int rotateRight = 2131034116;
			
			// aapt resource value: 0x7f050001
			public static int save = 2131034113;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public static int CropImage = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040003
			public static int discard = 2130968579;
			
			// aapt resource value: 0x7f040000
			public static int library_name = 2130968576;
			
			// aapt resource value: 0x7f040008
			public static int noStorageCard = 2130968584;
			
			// aapt resource value: 0x7f040006
			public static int notEnoughSpace = 2130968582;
			
			// aapt resource value: 0x7f040007
			public static int preparingCard = 2130968583;
			
			// aapt resource value: 0x7f040001
			public static int rotateLeft = 2130968577;
			
			// aapt resource value: 0x7f040002
			public static int rotateRight = 2130968578;
			
			// aapt resource value: 0x7f040004
			public static int save = 2130968580;
			
			// aapt resource value: 0x7f040005
			public static int savingImage = 2130968581;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
